name: Build Plated Pages
on: [push]
jobs:
  Build-Plated-Pages:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Do stuff
        run: |
          git config --global user.email "plated@gihub.actions"
          git config --global user.name "plated"
          plated/upgrade
          plated/build
          cd docs
          git add .
          git commit -mauto
          git push
        shell: bash
